Repository Brain-up/brn, pull requests merged in 2022-10, with the labels that each got.

#2266 2255 add fields "spentTime" and "doneExercises" to response for user with analytics
  api-contract/samples/user_with_analytics_get_response.json
  src/main/kotlin/com/epam/brn/model/StudyHistory.kt
  src/main/kotlin/com/epam/brn/model/projection/UserStatisticView.kt
  src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
  src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
  src/main/resources/db/migration/V220220802_2255.sql
  src/test/kotlin/com/epam/brn/service/UserAnalyticsServiceTest.kt
Labels: backend

#2331 2286 [BE] Prepare sql script to addd surdo/speech specialists into Contributor table #2286
  src/main/resources/db/migration/V220221011_2286.sql
  src/main/resources/db/migration/V220221012_2286.sql
Labels: java, backend, content

#2343 2281 [BE] Design and Implement getting contributors from our github project, save them into our DB, prepare api for getting them to our front #2281
  .github/workflows/certbot-update-cert.yml
  .github/workflows/docker-build-push-redeploy.yml
  Dockerfile
  build.gradle.kts
  docker-compose-run.yml
  gradle.properties
  src/main/kotlin/com/epam/brn/Application.kt
  src/main/kotlin/com/epam/brn/config/ConfigurationPropertiesConfig.kt
  src/main/kotlin/com/epam/brn/dto/github/GitHubContributorDto.kt
  src/main/kotlin/com/epam/brn/dto/github/GitHubUserDto.kt
  src/main/kotlin/com/epam/brn/job/GitHubContributorRefreshJob.kt
  src/main/kotlin/com/epam/brn/model/Contributor.kt
  src/main/kotlin/com/epam/brn/model/GitHubUser.kt
  src/main/kotlin/com/epam/brn/repo/ContributorRepository.kt
  src/main/kotlin/com/epam/brn/repo/GitHubUserRepository.kt
  src/main/kotlin/com/epam/brn/service/ContributorService.kt
  src/main/kotlin/com/epam/brn/service/ContributorServiceImpl.kt
  src/main/kotlin/com/epam/brn/webclient/GitHubApiClient.kt
  src/main/kotlin/com/epam/brn/webclient/config/GitHubApiClientConfig.kt
  src/main/kotlin/com/epam/brn/webclient/customizer/WebClientLoggingCustomizer.kt
  src/main/kotlin/com/epam/brn/webclient/property/GitHubApiClientProperty.kt
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/kotlin/com/epam/brn/job/GitHubContributorRefreshJobTest.kt
  src/test/kotlin/com/epam/brn/service/ContributorServiceTest.kt
  src/test/kotlin/com/epam/brn/webclient/GitHubApiClientTest.kt
  src/test/resources/application.properties
  src/test/resources/inputData/githubapi/contributors-2.json
  src/test/resources/inputData/githubapi/contributors.json
  src/test/resources/inputData/githubapi/http-error.json
  src/test/resources/inputData/githubapi/user.json
Labels: java, backend

#2349 2281 BE: Fix github token errors
  src/main/kotlin/com/epam/brn/job/GitHubContributorRefreshJob.kt
  src/main/kotlin/com/epam/brn/webclient/GitHubApiClient.kt
  src/main/kotlin/com/epam/brn/webclient/property/GitHubApiClientProperty.kt
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/kotlin/com/epam/brn/webclient/GitHubApiClientTest.kt
  src/test/resources/application.properties
Labels: bug, backend
