Repository Brain-up/brn, pull requests merged in 2022-08, with the labels that each got.

#2262 #2261: [UI Admin] Fix statistic values in table
  frontend-angular/src/app/modules/admin/modules/users/modules/statistics/components/daily-time-table/daily-time-table.component.ts
  frontend-angular/src/app/modules/admin/modules/users/modules/statistics/components/week-time-track/week-time-track.component.spec.ts
  frontend-angular/src/app/modules/admin/modules/users/modules/statistics/components/week-time-track/week-time-track.component.ts
Labels: bug, admin panel

#2267 2265 remove deprecated methods
  api-contract/api.raml
  frontend/app/adapters/user-weekly-statistics.ts
  frontend/app/adapters/user-yearly-statistics.ts
  frontend/mirage/config.js
  frontend/tests/acceptance/task-flow/tasks-flow-test.js
  frontend/tests/integration/components/statistics/component-test.js
  src/main/kotlin/com/epam/brn/controller/AdminController.kt
  src/main/kotlin/com/epam/brn/controller/StudyHistoryController.kt
  src/main/kotlin/com/epam/brn/controller/UserStatisticController.kt
  src/main/kotlin/com/epam/brn/controller/UserStatisticControllerV2.kt
  src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
  src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
  src/main/kotlin/com/epam/brn/service/statistic/impl/UserDayStatisticService.kt
  src/main/kotlin/com/epam/brn/service/statistic/impl/UserMonthStatisticService.kt
  src/main/kotlin/com/epam/brn/service/statistic/progress/status/impl/UserRestTimeRetrieverImpl.kt
  src/test/kotlin/com/epam/brn/integration/AdminControllerIT.kt
  src/test/kotlin/com/epam/brn/integration/AdminControllerV2IT.kt
  src/test/kotlin/com/epam/brn/integration/StudyHistoryControllerIT.kt
  src/test/kotlin/com/epam/brn/integration/UserStatisticControllerIT.kt
  src/test/kotlin/com/epam/brn/service/StudyHistoryServiceTest.kt
  src/test/kotlin/com/epam/brn/service/statistic/progress/UserDayStatisticServiceTest.kt
  src/test/kotlin/com/epam/brn/service/statistic/progress/UserMonthStatisticServiceTest.kt
  src/test/kotlin/com/epam/brn/service/statistic/progress/status/impl/UserRestTimeRetrieverImplTest.kt
Labels: backend, admin panel, web

#2246 2240 picture clear job
  src/main/kotlin/com/epam/brn/job/UnverifiedPicturesClearJob.kt
  src/main/kotlin/com/epam/brn/service/cloud/AwsCloudService.kt
  src/main/kotlin/com/epam/brn/service/cloud/CloudService.kt
  src/main/kotlin/com/epam/brn/service/cloud/GoogleCloudService.kt
  src/main/resources/application.properties
  src/test/kotlin/com/epam/brn/job/UnverifiedPicturesClearJobTest.kt
  src/test/kotlin/com/epam/brn/service/cloud/AwsCloudServiceTest.kt
  src/test/resources/application.properties
Labels: backend

#2289 2288 [BE] Fix bug: statistic page is not working for users, only for admins
  src/main/kotlin/com/epam/brn/config/WebSecurityBasicConfiguration.kt
  src/test/kotlin/com/epam/brn/integration/StudyHistoryControllerV2IT.kt
  src/test/kotlin/com/epam/brn/integration/UserStatisticControllerV2IT.kt
Labels: bug, backend

#2287 Added contributor model, repo, service, dto, controller
  src/main/kotlin/com/epam/brn/controller/ContributorController.kt
  src/main/kotlin/com/epam/brn/dto/ContactDto.kt
  src/main/kotlin/com/epam/brn/dto/GitHubUserDto.kt
  src/main/kotlin/com/epam/brn/dto/response/ContributorDetailsResponse.kt
  src/main/kotlin/com/epam/brn/dto/response/ContributorResponse.kt
  src/main/kotlin/com/epam/brn/enums/ContactType.kt
  src/main/kotlin/com/epam/brn/enums/ContributorType.kt
  src/main/kotlin/com/epam/brn/model/Contact.kt
  src/main/kotlin/com/epam/brn/model/Contributor.kt
  src/main/kotlin/com/epam/brn/model/GitHubUser.kt
  src/main/kotlin/com/epam/brn/repo/ContributorRepository.kt
  src/main/kotlin/com/epam/brn/service/ContributorService.kt
  src/main/kotlin/com/epam/brn/service/GitHubContributorService.kt
  src/main/resources/db/migration/V220220817_2281.sql
Labels: backend

#2280 2273 UI Angular show last day statistic in stat graphic
  frontend-angular/src/app/modules/admin/modules/users/modules/statistics/components/week-time-track/week-time-track.component.html
  frontend-angular/src/app/modules/admin/modules/users/modules/statistics/components/week-time-track/week-time-track.component.spec.ts
  frontend-angular/src/app/modules/admin/modules/users/modules/statistics/components/week-time-track/week-time-track.component.ts
  frontend-angular/src/app/modules/admin/modules/users/users.component.spec.ts
  frontend-angular/src/app/modules/admin/services/api/admin-api.service.fake.ts
  frontend-angular/src/app/modules/shared/components/bar-chart/bar-chart.component.spec.ts
  frontend-angular/src/app/modules/shared/components/bar-chart/bar-chart.component.ts
Labels: admin panel

#2274 2272 UI Ember user daily statistic table ember
  frontend/app/adapters/user-daily-time-table-statistics.ts
  frontend/app/components/statistics/bar-chart/component.ts
  frontend/app/components/statistics/daily-time-table/component.ts
  frontend/app/components/statistics/daily-time-table/styles.css
  frontend/app/components/statistics/daily-time-table/template.hbs
  frontend/app/components/statistics/month-time-track/component.ts
  frontend/app/components/statistics/week-time-track/component.ts
  frontend/app/components/statistics/week-time-track/styles.css
  frontend/app/components/statistics/week-time-track/template.hbs
  frontend/app/models/user-daily-time-table-statistics.ts
  frontend/app/serializers/user-daily-time-table-statistics.ts
  frontend/package.json
  frontend/tests/acceptance/task-flow/tasks-flow-test.js
  frontend/tests/unit/adapters/user-daily-time-table-statistics.js
  frontend/tests/unit/models/user-daily-time-table-statistics.js
  frontend/translations/en-us.yaml
  frontend/translations/ru-ru.yaml
Labels: web
